### PR TITLE
[NFC] Add GitHub check for YAML formatting

### PR DESCRIPTION
**Pull request by der-eismann**
While boulder creates the `stone.yml` files, the `monitoring.yml` files were often copy-pasted and mistakes were multiplying. This PR would add a check for the formatting of these files and also fix all existing ones. WDYT?

Examples: [ok](https://github.com/der-eismann/main/actions/runs/4558137358/jobs/8040657188) | [not ok](https://github.com/der-eismann/main/actions/runs/4557992545/jobs/8040346866)

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
LGTM, I'll let Ikey merge it though

**Comment by ReillyBrogan** [comment]
Actually, let me think about this a bit first.

**Comment by ReillyBrogan** [comment]
OK, let's break this into a few logical chunks (IE separate PRs):
- Fix any monitoring.yml files with invalid formatting
- Introduce prettier, ran by go-task (I expect there to be a discussion on said formatting here which is why I want to split this out)
- Fix the formatting on the files that we want it to manage (using either .editorconfig or .prettierrc)
- Add Github Actions along with the Docker image to run the tooling

How does that sound to you?

**Comment by der-eismann** [comment]
Sounds fine to me!

**Pull request closed without merging**
