### PR TITLE
docker

### PR DESCRIPTION
**Pull request by ReillyBrogan**
- virt/containerd: Update to v1.6.16
- virt/moby: Add at v23.0.0
- virt/docker-buildx: Add at v0.10.2
- virt/docker: Add at v23.0.0

Depends on https://github.com/snekpit/kernel/pull/4

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
Nothing wrong with this, they just released 23.0.0 so I figure I'll bite the bullet and use that.

**Comment by ReillyBrogan** [comment]
Note that virtiofs is missing some overlayfs feature required for docker. To workaround this you can mount another filesystem at /var/lib/docker, the following is a valid workaround:
```
fallocate -l 4gb docker.img
mkfs -t ext4 docker.img
mount docker.img /var/lib/docker
systemctl restart docker
```

**Comment by ikeycode** [comment]
LGTM :) I think we want to hold off adding any more users after this until moss-triggers can unfudge it..?

**Comment by ReillyBrogan** [comment]
> I think we want to hold off adding any more users after this until moss-triggers can unfudge it..?

Why would this be necessary?

**Pull request merged**
