### PR TITLE
libs/qt5/qt5-base: Add at v5.15.8

### PR DESCRIPTION
**Pull request by ReillyBrogan**
Signed-off-by: Reilly Brogan <reilly@reillybrogan.com>

### CODE REVIEW

**Comment by livingsilver94** [comment]
Shouldn't this belong to the plasma repository?

**Comment by ReillyBrogan** [comment]
> Shouldn't this belong to the plasma repository?

@ikeycode ^ . I thought we said this was going in main? I'm fine with either, this package is going to fall under the Plasma domain regardless.

**Comment by ikeycode** [comment]
I feel keeping it in main/ ensures that Qt works for the whole distro rather than just Plasma, esp given that Calamares will be in main. If you guys feel it needs to live in plasma for the sake of ease of maintenance then do so, as long as we eventually test of cases outside of Plasma use.

**Comment by livingsilver94** [comment]
It's purely a matter of consistency. If we are going to put qt5 in main, then we'll put gtk3/4 in there as well, and not in the gnome repo. A counterexample I can bring you is: what if we'll develop a SerpentOS-specific utility written in GTK? This is the same condition as Calamares'. It's either we have Qt and GTK here, or both in their own repos, IMO.

**Comment by joebonrichie** [comment]
System harfbuzz package available now

**Comment by ikeycode** [comment]
new boulder has been deployed - merging this beauty. I'll enable system harfbuzz ^^

**Pull request merged**
