### PR TITLE
Release manager cleanups

### PR DESCRIPTION
**Pull request by ReillyBrogan**
vim, file, btrfs-progs, and python-pytz got updated to newer versions.
libedit, curl, inxi, and openssh got their version fixed so that it matches upstream.
systemd and shadow got ignores to match that they are being held back to a previous stable release currently.

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
Note that boulder doesn't seem to like the curl version string. Seems to turn it from `7_87_0` to `7870`.

**Comment by ikeycode** [comment]
Even if the string is quoted?

**Comment by ReillyBrogan** [comment]
> Even if the string is quoted?

Nope, that fixed it.

**Comment by der-eismann** [comment]
> Note that boulder doesn't seem to like the curl version string. Seems to turn it from `7_87_0` to `7870`.

I changed the release-monitoring entry for curl so it is back to the correct version format

**Comment by ReillyBrogan** [comment]
> > Note that boulder doesn't seem to like the curl version string. Seems to turn it from `7_87_0` to `7870`.
> 
> I changed the release-monitoring entry for curl so it is back to the correct version format

OK, I fixed it.

**Comment by ReillyBrogan** [comment]
`7_87_0` was hideous anyway.

**Comment by ikeycode** [comment]
lgtm! ty!

**Pull request merged**
