### PR TITLE
Add OpenSSH

### PR DESCRIPTION
**Pull request by ReillyBrogan**
Tested:
- Using `ssh` to log into another Linux host
- Setting the ssh port to 2222 and starting it from within the systemd-nspawn
- SSHing in as root with password (after removing the restriction on not allowing root to login with passwords)
- SSHing in as root with authorized_keys

libedit and ldns need to be build first.

### CODE REVIEW

**Review by ermo — COMMENTED** [review]
With `mv %(installroot)/etc/ssh %(installroot)/%(vendordir)/` it occurs to me that the dir and file permissions might be subject to umask.

A better approach might be `cp -av`, which preserves attributes, followed by `rm -rf`. Some of the stuff under /etc/ssh is not supposed to be world-readable IME.

**Comment by ReillyBrogan** [comment]
> A better approach might be `cp -av`, which preserves attributes, followed by `rm -rf`. Some of the stuff under /etc/ssh is not supposed to be world-readable IME.

Not really an issue with this package because none of the `/etc/` files shipped are sensitive (it's mostly the host key files that are sensitive and they are generated via the ssh-keygen service, OpenSSH will also refuse to use any files with incorrect permissions).

However, I did just notice that I still have moduli in the `openssh` package when it should be in the `openssh-server` package, going to mark this as a draft until I correct that.

**Comment by ikeycode** [comment]
LGTM - thx

**Comment by ikeycode** [comment]
all built!

**Pull request merged**
